import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LenisConext from "@/contexts/lenis-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-cod-gray text-demo-smoke">
      <body className={inter.className}>
        <LenisConext >{children}</LenisConext>
      </body>
    </html>
  );
}
